// names.js

export const  names = {
    pl: {
      title: "Zarządzanie infrastrukturą sieciową",
      selector: "Wybór stron",
      appInwentory: "Ewidencja urządzeń sieciowych",
      appAdd: "Dodaj urządzenie",
      appDelete: "Usuń urządzenie",
      appModify: "Modyfikuj urządzenie",
      appGraph: "Graf połączeń logicznych",
      appMonitoring: "Monitoring urządzeń sieciowych",
      delete: "Usuń",
      add: "Dodaj",
      routers: "Routery",
      switches: "Przełączniki",
      servers: "Serwery",
      accessPoints: "Punkty Dostępowe",
      computers: "Komputery",
      devices: "Urządzenia sieciowe",
      searchDeviceByID: "Wyszukaj urządzenie po ID",
      logIn:"Zaloguj się",
      logOut: "wyloguj się",
      switchToLightMode: "Przełącz w tryb jasny",
      switchToDarkMode: "Przełącz w tryb ciemny",
      ID: "ID",
      medium: "Medium",
      transmisionSpeed:"Prędkość transmisji",
      addProduct: "Dodaj Urządzenie",
      addPort: "Dodaj Port",
      select: "Wybierz",
      DeviceType: "Typ urządzenia sieciowego",
      ProductID : "ID urządzenia",
      IdInsideWFiIS: "ID wewnątrz wydziałowej sieci",
      PortsList: "Lista portów",
      remove: "Usuń",
      deleteDevice: "Usuń urządzenie",
      portID: "ID portu",
      selectDeviceToUpdate: "wybierz urządzenie sieciowe które chcesz modyfikować",
      searchByType: "Wyszukaj po typie",
      searchById: "Wyszukaj po ID",
      savePositions: "Zapisz pozycje",
      selectDeviceType: "Wybierz typ urządzenia",
      addPort: "Dodaj port",
    },
    en: {
      title: "Network Infrastructure Management",
      selector: "Page Selector",
      appInwentory: "Network Device Inventory",
      appAdd: "Add Device",
      appDelete: "Delete Device",
      appModify: "Update Device",
      appGraph: "Logical Connections Graph",
      appMonitoring: "Network Device Monitoring",
      delete: "delete",
      add: "Add",
      routers: "Routers",
      switches: "Switches",
      servers: "Servers",
      accessPoints: "Access Points",
      computers: "Computers",
      devices: "Devices",
      searchDeviceByID: "Search device by ID",
      logIn:"Log in",
      logOut: "Log Out",
      switchToLightMode: "Switch to Light Mode",
      switchToDarkMode: "Switch to Dark Mode",
      ID: "ID",
      medium: "Medium",
      transmisionSpeed:"Transmision Speed",
      addProduct: "Add Product",
      addPort: "App Port",
      select: "Select",
      DeviceType: "Device Type",
      ProductID : "Product ID",
      IdInsideWFiIS: "ID inside WFiIS NET",
      PortsList: "Port List",
      remove: "Remove",
      deleteDevice: "Delete Device",
      portID: "Port ID",
      selectDeviceToUpdate: "Select Device to update",
      searchByType: "Search by type",
      searchById: "Search by ID",
      savePositions: "Save coordinates",
      selectDeviceType: "Select Device Type",
      addPort: "Add port",
    }
  };
  