spring:
  application:
    name: App-Metrics
  security:
    user:
      name: user1
      password: password

# configs to connect to self register the admin server as a client
spring.boot.admin.client:
  url: http://keycloak:8080,http://ewidencja:8090,http://graf:8089,http://eureka:8761,http://gateway:8222,http://monitoring:8091,
  username: ${spring.security.user.name}
  password: ${spring.security.user.password}

# configs to give secured server info
spring.boot.admin.client.instance.metadata:
  user.name: ${spring.security.user.name}
  user.password: ${spring.security.user.password}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

spring.boot.admin.routes.endpoints: env, metrics, trace, jolokia, info, configprops
server:
  port: 9090

eureka:
  instance:
    hostname: eureka
    metadata-map:
      user.name: user1
      user.password: password
  client:
    service-url:
      defaultZone: http://user1:password@eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
