server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  security:
    user:
      name: user1
      password: password
      roles: USER
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations